name: ChatOps
on: [issue_comment]

jobs:
  full-test-run:
    if: github.event.issue.pull_request != null &&  contains(github.event.comment.body, '/run-full-test')
    runs-on: ubuntu-latest
    steps:
      - uses: machine-learning-apps/actions-chatops@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}
          TRIGGER_PHRASE: "/run-full-test"
          INDICATOR_LABEL: "Full Test Pending"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    if: github.event.issue.pull_request != null &&  contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:

      - uses: machine-learning-apps/actions-chatops@master
        id: deploy_chatops
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}
          TRIGGER_PHRASE: "/deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: validate deploy argument
        uses: machine-learning-apps/wandb-action@master
        if: steps.deploy_chatops.outputs.TRIGGERED == 'true'
        id: wandb
        with:
          PROJECT_NAME: ${{ format('{0}/{1}', secrets.WANDB_ENTITY, secrets.WANDB_PROJECT) }}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          RUN_ID: ${{ steps.deploy_chatops.outputs.TRAILING_TOKEN }}
          DEBUG: 'true'
        
      - name: create deployment
        if: steps.wandb.outputs.BOOL_SINGLE_RUN
        run: |
          curl -d '{"ref": "$BRANCH_NAME", "payload": {"run_id": "$RUN_ID"}}' -H "Authorization: token $TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/deployments
        env:
          RUN_ID: ${{ steps.deploy_chatops.outputs.TRAILING_TOKEN }}
          BRANCH_NAME: ${{ steps.deploy_chatops.outputs.BRANCH_NAME }}
          TOKEN: ${{ steps.deploy_chatops.outputs.APP_INSTALLATION_TOKEN }}

      