name: Get token for prototyping
on: push

jobs:
  test:
    name: see-token
    runs-on: ubuntu-latest

    steps:
    - name: change env
      run: echo "GITHUB_SHA - $GITHUB_SHA"
      env:
        GITHUB_SHA: "hamel"

    - name: Write token
      run: | 
        echo $GITHUB_TOKEN > tok.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload payload
      uses: actions/upload-artifact@v1
      with:
        name: token
        path: tok.txt
